### ISSUE TITLE
Issue runnig examples (AttributeError: 'module' object has no attribute 'clipper_cc')

### ISSUE THREAD

**Issue by steven-bloom** [gercap/gr-ofdm_tools#1]
Hi everyone!
first of all i would like to thank you for this wonderful tool. 
However, i face the problem when running Example:

self.ofdm_tools_clipper_0 = ofdm_tools.clipper_cc(clipping_factor)
AttributeError: 'module' object has no attribute 'clipper_cc'

Could you please help me to get over this?
![screenshot from 2017-10-28 17-58-41](https://user-images.githubusercontent.com/30798903/32136092-b2bb20ae-bc09-11e7-8c35-29d4a031e132.png)

**Comment by gercap** [comment]
the clipper block is a deprecated block I created (as an exercise) as I didn't know gnuradio core block "Rail" can basically do the same with some adjustments.
I created a new clipper block so all dependent blocks work seamlessly.
I also adjusted RadioA example for a quicker result (the baseband complex stream is looped).
